#! /bin/bash

CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "${COMMIT_RANGE}")

if ! echo "${CHANGED_FILES}" | grep -qE "^(\\.php-cs-fixer(\\.dist)?\\.php|composer\\.lock)$"; then
    EXTRA_ARGS=$(printf -- '--path-mode=intersection\n--\n%s' "${CHANGED_FILES}");
else
    EXTRA_ARGS='';
fi

$(dirname "${BASH_SOURCE[0]}")/vendor/bin/php-cs-fixer fix $1 ${EXTRA_ARGS}
